#############################################################
# TCGA-BRCA Survival Analysis of Top Differentially Expressed Genes
#
# Extends the existing TCGA-BRCA DESeq2 differential expression
# pipeline (tumor vs. normal) by testing whether expression levels
# of the top DEGs are associated with patient survival outcomes.
#
# Author: Gunika Nagpal
# Input:  DESeq2 results (from prior TCGA-BRCA DEG pipeline) +
#         TCGA-BRCA clinical metadata (via recount3)
# Output: Kaplan-Meier survival plots, log-rank test results,
#         and a Cox proportional hazards summary table
#############################################################

## ---- 0. Packages -------------------------------------------------
# Install once if needed:
# install.packages(c("survival", "survminer", "dplyr", "readr"))
# if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
# BiocManager::install("recount3")

library(recount3)
library(survival)
library(survminer)
library(dplyr)
library(readr)
library(readxl)
library(janitor)   # install.packages("janitor") - used for clean_names()

## ---- 1. Load clinical + expression data via recount3 -------------
# Pulls the same TCGA-BRCA project used in the original DESeq2 pipeline.
# recount3 bundles clinical/phenotype metadata alongside expression data,
# so no separate clinical file download is needed.

brca_proj <- available_projects(organism = "human") |>
  dplyr::filter(project == "BRCA", project_type == "data_sources")

rse_brca <- create_rse(brca_proj)

# Normalize raw coverage counts to read counts
assay(rse_brca, "counts") <- transform_counts(rse_brca)

## ---- 2. Extract clinical/survival variables -----------------------
# Key TCGA fields needed for survival analysis:
#   vital_status         : "Alive" / "Dead"
#   days_to_death         : follow-up time if deceased
#   days_to_last_followup : follow-up time if alive
clinical <- as.data.frame(colData(rse_brca)) %>%
  dplyr::select(
    external_id = tcga.tcga_barcode,
    sample_type = tcga.cgc_sample_sample_type,
    vital_status = tcga.cgc_case_vital_status,
    days_to_death = tcga.cgc_case_days_to_death,
    days_to_last_followup = tcga.cgc_case_days_to_last_followup
  ) %>%
  # Keep only primary tumor samples (survival is only meaningful for tumor cases)
  dplyr::filter(sample_type == "Primary Tumor") %>%
  dplyr::mutate(
    time = ifelse(vital_status == "Dead", days_to_death, days_to_last_followup),
    status = ifelse(vital_status == "Dead", 1, 0)   # 1 = event (death), 0 = censored
  ) %>%
  dplyr::filter(!is.na(time), time > 0)

## ---- 3. Load top DEGs from your existing DESeq2 results -----------
# Reads the significant-DEGs results file already generated by the
# original TCGA-BRCA DESeq2 pipeline (results/ folder in the repo).
# Column names are auto-detected below since export naming can vary
# (e.g. "gene_id" vs "GeneID", "padj" vs "adj.P.Val", etc.)

deg_results_raw <- read_excel("../results/DEG_results_TCGA_A_SIGNIFICANT_ONLY.xlsx")
deg_results <- deg_results_raw %>% janitor::clean_names()   # lowercases + underscores all column names

# --- Auto-detect the 3 columns we need ---
find_col <- function(df, candidates) {
  hit <- candidates[candidates %in% names(df)]
  if (length(hit) == 0) {
    stop(
      "Could not find a matching column. Looked for: ", paste(candidates, collapse = ", "),
      "\nActual columns in file: ", paste(names(df), collapse = ", ")
    )
  }
  hit[1]
}

gene_col   <- find_col(deg_results, c("gene_id", "geneid", "gene", "ensembl_id", "ensembl_gene_id", "symbol", "gene_symbol", "row_names", "x1"))
lfc_col    <- find_col(deg_results, c("log2foldchange", "log2fc", "logfc", "log2_fold_change"))
padj_col   <- find_col(deg_results, c("padj", "adj_p_val", "adjusted_p_value", "fdr", "qvalue", "p_adj"))

cat("Using columns -> gene:", gene_col, "| log2FC:", lfc_col, "| padj:", padj_col, "\n")

top_degs <- deg_results %>%
  dplyr::filter(!is.na(.data[[padj_col]]), .data[[padj_col]] < 0.05, abs(.data[[lfc_col]]) > 1) %>%
  dplyr::arrange(.data[[padj_col]]) %>%
  dplyr::slice_head(n = 10) %>%     # top 10 most significant DEGs
  dplyr::pull(.data[[gene_col]])

## ---- 4. Build expression matrix for those genes -------------------
expr_counts <- assay(rse_brca, "counts")
expr_subset <- expr_counts[rownames(expr_counts) %in% top_degs, , drop = FALSE]

# Match sample IDs between expression matrix and clinical data
common_samples <- intersect(colnames(expr_subset), clinical$external_id)
expr_subset <- expr_subset[, common_samples, drop = FALSE]
clinical <- clinical %>% dplyr::filter(external_id %in% common_samples)
clinical <- clinical[match(colnames(expr_subset), clinical$external_id), ]

## ---- 5. Run Kaplan-Meier + log-rank test per gene ------------------
# Splits patients into "High" vs "Low" expression groups using the
# median expression value for each gene, then tests whether survival
# differs significantly between the two groups.

results_summary <- list()
dir.create("plots", showWarnings = FALSE)

for (gene in rownames(expr_subset)) {

  expr_vals <- as.numeric(expr_subset[gene, ])
  median_expr <- median(expr_vals, na.rm = TRUE)

  group <- ifelse(expr_vals >= median_expr, "High", "Low")

  surv_df <- data.frame(
    time = clinical$time,
    status = clinical$status,
    group = group
  )

  fit <- survfit(Surv(time, status) ~ group, data = surv_df)
  logrank <- survdiff(Surv(time, status) ~ group, data = surv_df)
  p_value <- 1 - pchisq(logrank$chisq, df = 1)

  # Cox proportional hazards model (continuous expression, not binned)
  cox_df <- data.frame(
    time = clinical$time,
    status = clinical$status,
    expr = expr_vals
  )
  cox_fit <- coxph(Surv(time, status) ~ expr, data = cox_df)
  cox_summary <- summary(cox_fit)

  results_summary[[gene]] <- data.frame(
    gene = gene,
    logrank_p = p_value,
    cox_hazard_ratio = cox_summary$coefficients[, "exp(coef)"],
    cox_p = cox_summary$coefficients[, "Pr(>|z|)"]
  )

  # Save KM plot for genes with significant log-rank test
  if (p_value < 0.05) {
    p <- ggsurvplot(
      fit,
      data = surv_df,
      pval = TRUE,
      risk.table = TRUE,
      title = paste("Kaplan-Meier Survival:", gene),
      xlab = "Time (days)",
      legend.title = "Expression",
      palette = c("High" = "#D95F02", "Low" = "#1B9E77")
    )
    ggsave(
      filename = file.path("plots", paste0("KM_", gene, ".png")),
      plot = p$plot,
      width = 7, height = 5, dpi = 300
    )
  }
}

## ---- 6. Save combined results table --------------------------------
final_results <- dplyr::bind_rows(results_summary) %>%
  dplyr::arrange(logrank_p)

write_csv(final_results, "survival_analysis_results.csv")

cat("\nDone. Significant genes (log-rank p < 0.05):\n")
print(final_results %>% dplyr::filter(logrank_p < 0.05))

cat("\nKM plots saved to ./plots/\n")
cat("Full results table saved to survival_analysis_results.csv\n")
